### ISSUE TITLE
Setup Gui

### ISSUE THREAD

**Issue by jakedur** [jakedur/questForFloyda#1]
gui's are funnnnnnn

**Comment by jakedur** [comment]
Had to redo a lot of weird stuff to be able to have the gui, prepare for a weird merge soon.

**Comment by RyanAdelman-Drummond** [comment]
okay well i am just adding frame work to the items and characters let me know when you are going to do that before you do it so i can push all of my changes and you can get them

**Comment by jakedur** [comment]
finished a while ago
